# Generated by Django 3.0.4 on 2020-03-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(help_text='Must be a 10 digit number', max_length=10)),
                ('photo', models.ImageField(upload_to='media/', verbose_name='Photo')),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captureEdge.Claim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(help_text='Must be a 10 digit number', max_length=10)),
                ('claim_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captureEdge.Claim')),
            ],
            options={
                'unique_together': {('claim_id', 'phone')},
            },
        ),
    ]
