# Generated by Django 3.0.4 on 2020-03-16 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureEdge', '0003_auto_20200316_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Must be a 10 digit number', max_length=13, unique=True),
        ),
    ]
