# Generated by Django 3.0.4 on 2020-03-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureEdge', '0004_auto_20200316_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Must be a 10 digit number', max_length=13),
        ),
        migrations.AlterUniqueTogether(
            name='phone',
            unique_together={('claim_id', 'phone')},
        ),
    ]
