# Generated by Django 3.0.4 on 2020-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureEdge', '0005_auto_20200316_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone',
            field=models.CharField(help_text='Must be a 10 digit number', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.related.ForeignKey>', verbose_name='Image'),
        ),
    ]
