# Generated by Django 3.0.4 on 2020-03-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captureEdge', '0006_auto_20200317_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='phone',
            field=models.CharField(help_text='Must be a 10 digit number', max_length=10),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Photo'),
        ),
    ]
